apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-demo-preview
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    # ingress.kubernetes.io/proxy-body-size: 100M
    # kubernetes.io/ingress.class: "nginx"
    # ingress.kubernetes.io/app-root: "/"
spec:
  rules:
  - host: canary-preview.test.
    http:
      paths:
      - path: /
        backend:
          serviceName: canary-demo-preview
          servicePort: 80